qlib_init:
  provider_uri: /home/song/projects/ib-qlib-pipeline/data/qlib/us_data_custom
  region: us

market: &market all
benchmark: &benchmark SPY

data_handler_config: &data_handler_config
  start_time: 2016-01-04
  end_time: 2026-03-06
  fit_start_time: 2016-01-04
  fit_end_time: 2022-12-30
  instruments: *market

task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      colsample_bytree: 0.8879
      learning_rate: 0.0421
      subsample: 0.8789
      lambda_l1: 205.6999
      lambda_l2: 580.9768
      max_depth: 8
      num_leaves: 210
      num_threads: 4
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs: *data_handler_config
      segments:
        train: [2016-01-04, 2022-12-30]
        valid: [2023-01-03, 2024-12-31]
        test: [2025-01-02, 2026-03-06]
  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs: {}
    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs: {}
