qlib_init:
  provider_uri: /home/song/projects/ib-qlib-pipeline/data/qlib/us_data_news_full
  region: us

market: &market all
benchmark: &benchmark AAPL

data_handler_config: &data_handler_config
  start_time: 2020-01-02
  end_time: 2026-03-06
  fit_start_time: 2020-01-02
  fit_end_time: 2023-12-29
  instruments: *market
  news_fields: [news_count, news_sentiment]

port_analysis_config: &port_analysis_config
  strategy:
    class: TopkDropoutStrategy
    module_path: qlib.contrib.strategy
    kwargs:
      signal: <PRED>
      topk: 50
      n_drop: 5
  backtest:
    start_time: 2025-01-02
    end_time: 2026-03-06
    account: 100000000
    benchmark: *benchmark
    exchange_kwargs:
      limit_threshold: 0.095
      deal_price: close
      open_cost: 0.0005
      close_cost: 0.0015
      min_cost: 5

task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      colsample_bytree: 0.6
      learning_rate: 0.05
      subsample: 0.7
      lambda_l1: 100.0
      lambda_l2: 0.0
      max_depth: 10
      num_leaves: 255
      min_child_samples: 40
      num_threads: 4
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158News
        module_path: ib_qlib_pipeline.handlers
        kwargs: *data_handler_config
      segments:
        train: [2020-01-02, 2023-12-29]
        valid: [2024-01-02, 2024-12-31]
        test: [2025-01-02, 2026-03-06]
  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs: {}
    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config
